/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sat Jun 02 22:07:35 CDT 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package dao4j;

/*
 * For Table curso_has_usuario
 */
public class CursoHasUsuario implements java.io.Serializable, Cloneable {
    private CursoHasUsuarioKey _key = new CursoHasUsuarioKey();

    /* Curso_idCurso, PK */
    protected int cursoIdcurso;

    /* Usuario_idUsuarios, PK */
    protected int usuarioIdusuarios;

    /* Return the key object. */
    public CursoHasUsuarioKey getKeyObject() {
        return _key;
    }

    /* Curso_idCurso, PK */
    public int getCursoIdcurso() {
        return cursoIdcurso;
    }

    /* Curso_idCurso, PK */
    public void setCursoIdcurso(int cursoIdcurso) {
        this.cursoIdcurso = cursoIdcurso;
        _key.setCursoIdcurso(cursoIdcurso);
    }

    /* Usuario_idUsuarios, PK */
    public int getUsuarioIdusuarios() {
        return usuarioIdusuarios;
    }

    /* Usuario_idUsuarios, PK */
    public void setUsuarioIdusuarios(int usuarioIdusuarios) {
        this.usuarioIdusuarios = usuarioIdusuarios;
        _key.setUsuarioIdusuarios(usuarioIdusuarios);
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof CursoHasUsuario))
            return false;

        CursoHasUsuario bean = (CursoHasUsuario) obj;

        if (this.cursoIdcurso != bean.cursoIdcurso)
            return false;

        if (this.usuarioIdusuarios != bean.usuarioIdusuarios)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        CursoHasUsuario bean = new CursoHasUsuario();
        bean.cursoIdcurso = this.cursoIdcurso;
        bean.usuarioIdusuarios = this.usuarioIdusuarios;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("cursoIdcurso").append(" = ").append(cursoIdcurso).append("]").append(sep);
        sb.append("[").append("usuarioIdusuarios").append(" = ").append(usuarioIdusuarios).append("]").append(sep);
        return sb.toString();
    }
}