/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sat Jun 02 22:07:35 CDT 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package dao4j;

public class CursoKey implements java.io.Serializable, Cloneable {
    /* idCurso */
    protected int idcurso;

    /* idCurso */
    public int getIdcurso() {
        return idcurso;
    }

    /* idCurso */
    public void setIdcurso(int idcurso) {
        this.idcurso = idcurso;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        hashCode += new Integer(idcurso).hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof CursoKey))
            return false;

        CursoKey key = (CursoKey) obj;

        if (this.idcurso != key.idcurso)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        CursoKey key = new CursoKey();
        key.idcurso = this.idcurso;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idcurso").append(" = ").append(idcurso).append("]");
        return sb.toString();
    }
}