/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sat Jun 02 22:07:35 CDT 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package dao4j;

public class CursoHasUsuarioKey implements java.io.Serializable, Cloneable {
    /* Curso_idCurso */
    protected int cursoIdcurso;

    /* Usuario_idUsuarios */
    protected int usuarioIdusuarios;

    /* Curso_idCurso */
    public int getCursoIdcurso() {
        return cursoIdcurso;
    }

    /* Curso_idCurso */
    public void setCursoIdcurso(int cursoIdcurso) {
        this.cursoIdcurso = cursoIdcurso;
    }

    /* Usuario_idUsuarios */
    public int getUsuarioIdusuarios() {
        return usuarioIdusuarios;
    }

    /* Usuario_idUsuarios */
    public void setUsuarioIdusuarios(int usuarioIdusuarios) {
        this.usuarioIdusuarios = usuarioIdusuarios;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        hashCode += new Integer(cursoIdcurso).hashCode();
        hashCode += new Integer(usuarioIdusuarios).hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof CursoHasUsuarioKey))
            return false;

        CursoHasUsuarioKey key = (CursoHasUsuarioKey) obj;

        if (this.cursoIdcurso != key.cursoIdcurso)
            return false;

        if (this.usuarioIdusuarios != key.usuarioIdusuarios)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        CursoHasUsuarioKey key = new CursoHasUsuarioKey();
        key.cursoIdcurso = this.cursoIdcurso;
        key.usuarioIdusuarios = this.usuarioIdusuarios;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("cursoIdcurso").append(" = ").append(cursoIdcurso).append("]");
        sb.append("[").append("usuarioIdusuarios").append(" = ").append(usuarioIdusuarios).append("]");
        return sb.toString();
    }
}