/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sat Jun 02 22:07:35 CDT 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package dao4j;

/*
 * For Table examen
 */
public class Examen implements java.io.Serializable, Cloneable {
    private ExamenKey _key = new ExamenKey();

    /* idexamen, PK */
    protected int idexamen;

    /* calificacion */
    protected int calificacion;

    /* Return the key object. */
    public ExamenKey getKeyObject() {
        return _key;
    }

    /* idexamen, PK */
    public int getIdexamen() {
        return idexamen;
    }

    /* idexamen, PK */
    public void setIdexamen(int idexamen) {
        this.idexamen = idexamen;
        _key.setIdexamen(idexamen);
    }

    /* calificacion */
    public int getCalificacion() {
        return calificacion;
    }

    /* calificacion */
    public void setCalificacion(int calificacion) {
        this.calificacion = calificacion;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Examen))
            return false;

        Examen bean = (Examen) obj;

        if (this.idexamen != bean.idexamen)
            return false;

        if (this.calificacion != bean.calificacion)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Examen bean = new Examen();
        bean.idexamen = this.idexamen;
        bean.calificacion = this.calificacion;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idexamen").append(" = ").append(idexamen).append("]").append(sep);
        sb.append("[").append("calificacion").append(" = ").append(calificacion).append("]").append(sep);
        return sb.toString();
    }
}