/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sat Jun 02 22:07:35 CDT 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package dao4j;

public class PreguntaKey implements java.io.Serializable, Cloneable {
    /* idPregunta */
    protected int idpregunta;

    /* examen_idexamen */
    protected int examenIdexamen;

    /* RespuestaCorrecta */
    protected int respuestacorrecta;

    /* idPregunta */
    public int getIdpregunta() {
        return idpregunta;
    }

    /* idPregunta */
    public void setIdpregunta(int idpregunta) {
        this.idpregunta = idpregunta;
    }

    /* examen_idexamen */
    public int getExamenIdexamen() {
        return examenIdexamen;
    }

    /* examen_idexamen */
    public void setExamenIdexamen(int examenIdexamen) {
        this.examenIdexamen = examenIdexamen;
    }

    /* RespuestaCorrecta */
    public int getRespuestacorrecta() {
        return respuestacorrecta;
    }

    /* RespuestaCorrecta */
    public void setRespuestacorrecta(int respuestacorrecta) {
        this.respuestacorrecta = respuestacorrecta;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        hashCode += new Integer(idpregunta).hashCode();
        hashCode += new Integer(examenIdexamen).hashCode();
        hashCode += new Integer(respuestacorrecta).hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof PreguntaKey))
            return false;

        PreguntaKey key = (PreguntaKey) obj;

        if (this.idpregunta != key.idpregunta)
            return false;

        if (this.examenIdexamen != key.examenIdexamen)
            return false;

        if (this.respuestacorrecta != key.respuestacorrecta)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        PreguntaKey key = new PreguntaKey();
        key.idpregunta = this.idpregunta;
        key.examenIdexamen = this.examenIdexamen;
        key.respuestacorrecta = this.respuestacorrecta;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idpregunta").append(" = ").append(idpregunta).append("]");
        sb.append("[").append("examenIdexamen").append(" = ").append(examenIdexamen).append("]");
        sb.append("[").append("respuestacorrecta").append(" = ").append(respuestacorrecta).append("]");
        return sb.toString();
    }
}