/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sat Jun 02 22:07:35 CDT 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package dao4j;

public class UsuarioKey implements java.io.Serializable, Cloneable {
    /* idUsuarios */
    protected int idusuarios;

    /* idUsuarios */
    public int getIdusuarios() {
        return idusuarios;
    }

    /* idUsuarios */
    public void setIdusuarios(int idusuarios) {
        this.idusuarios = idusuarios;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        hashCode += new Integer(idusuarios).hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof UsuarioKey))
            return false;

        UsuarioKey key = (UsuarioKey) obj;

        if (this.idusuarios != key.idusuarios)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        UsuarioKey key = new UsuarioKey();
        key.idusuarios = this.idusuarios;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idusuarios").append(" = ").append(idusuarios).append("]");
        return sb.toString();
    }
}