/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sat Jun 02 22:07:35 CDT 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package dao4j.orm;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Types;
import java.util.List;
import java.util.ArrayList;
import dao4j.*;
import dao4j.dao.CursoHasUsuarioDAO;

/**
 * This class provides methods to populate DB Table of curso_has_usuario
 */
public class CursoHasUsuarioDAOImpl implements CursoHasUsuarioDAO {
    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO curso_has_usuario ("
        + "Curso_idCurso, Usuario_idUsuarios"
        + ") VALUES (?, ?)";

    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "Curso_idCurso, Usuario_idUsuarios "
        + "FROM curso_has_usuario WHERE "
        + "Curso_idCurso = ? AND Usuario_idUsuarios = ?";

    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE curso_has_usuario SET "
        + "WHERE "
        + "Curso_idCurso = ? AND Usuario_idUsuarios = ?";

    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM curso_has_usuario WHERE "
        + "Curso_idCurso = ? AND Usuario_idUsuarios = ?";

    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(CursoHasUsuario bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_INSERT);
            ps.setInt(1, bean.getCursoIdcurso());
            ps.setInt(2, bean.getUsuarioIdusuarios());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    public CursoHasUsuario load(CursoHasUsuarioKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT);
            ps.setInt(1, key.getCursoIdcurso());
            ps.setInt(2, key.getUsuarioIdusuarios());
            rs = ps.executeQuery();
            List results = getResults(rs);
            if (results.size() > 0)
                return (CursoHasUsuario) results.get(0);
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void update(CursoHasUsuario bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_UPDATE);
            ps.setInt(1, bean.getCursoIdcurso());
            ps.setInt(2, bean.getUsuarioIdusuarios());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(CursoHasUsuarioKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_DELETE);
            ps.setInt(1, key.getCursoIdcurso());
            ps.setInt(2, key.getUsuarioIdusuarios());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }
    
    /**
     * Populate the ResultSet.
     * @param rs     The ResultSet.
     * @return       The Object to retrieve from DB.
     * @exception    SQLException if something is wrong.
     */
    protected List<CursoHasUsuario> getResults(ResultSet rs) throws SQLException {
        List results = new ArrayList<CursoHasUsuario>();
        while (rs.next()) {
            CursoHasUsuario bean = new CursoHasUsuario();
            bean.setCursoIdcurso(rs.getInt("Curso_idCurso"));
            bean.setUsuarioIdusuarios(rs.getInt("Usuario_idUsuarios"));
            results.add(bean);
        }
        return results;
    }

    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    protected void close(Statement stmt) {
        if (stmt != null) {
            try {
                stmt.close();
            }catch(SQLException e){}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    protected void close(ResultSet rs) {
        if (rs != null) {
            try {
                rs.close();
            }catch(SQLException e){}
        }
    }
}