/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sat Jun 02 22:07:35 CDT 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package dao4j.orm;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Types;
import java.util.List;
import java.util.ArrayList;
import dao4j.*;
import dao4j.dao.RespuestaDAO;

/**
 * This class provides methods to populate DB Table of respuesta
 */
public class RespuestaDAOImpl implements RespuestaDAO {
    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO respuesta ("
        + "idRespuesta, texto, Pregunta_idPregunta"
        + ") VALUES (?, ?, ?)";

    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "idRespuesta, texto, Pregunta_idPregunta "
        + "FROM respuesta WHERE "
        + "idRespuesta = ? AND Pregunta_idPregunta = ?";

    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE respuesta SET "
        + "texto = ? "
        + "WHERE "
        + "idRespuesta = ? AND Pregunta_idPregunta = ?";

    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM respuesta WHERE "
        + "idRespuesta = ? AND Pregunta_idPregunta = ?";

    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Respuesta bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_INSERT);
            ps.setInt(1, bean.getIdrespuesta());
            ps.setString(2, bean.getTexto());
            ps.setInt(3, bean.getPreguntaIdpregunta());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    public Respuesta load(RespuestaKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT);
            ps.setInt(1, key.getIdrespuesta());
            ps.setInt(2, key.getPreguntaIdpregunta());
            rs = ps.executeQuery();
            List results = getResults(rs);
            if (results.size() > 0)
                return (Respuesta) results.get(0);
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void update(Respuesta bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_UPDATE);
            ps.setString(1, bean.getTexto());
            ps.setInt(2, bean.getIdrespuesta());
            ps.setInt(3, bean.getPreguntaIdpregunta());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(RespuestaKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_DELETE);
            ps.setInt(1, key.getIdrespuesta());
            ps.setInt(2, key.getPreguntaIdpregunta());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }
    
    /**
     * Populate the ResultSet.
     * @param rs     The ResultSet.
     * @return       The Object to retrieve from DB.
     * @exception    SQLException if something is wrong.
     */
    protected List<Respuesta> getResults(ResultSet rs) throws SQLException {
        List results = new ArrayList<Respuesta>();
        while (rs.next()) {
            Respuesta bean = new Respuesta();
            bean.setIdrespuesta(rs.getInt("idRespuesta"));
            bean.setTexto(rs.getString("texto"));
            if (rs.wasNull())
                bean.setTexto(null);     
            bean.setPreguntaIdpregunta(rs.getInt("Pregunta_idPregunta"));
            results.add(bean);
        }
        return results;
    }

    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    protected void close(Statement stmt) {
        if (stmt != null) {
            try {
                stmt.close();
            }catch(SQLException e){}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    protected void close(ResultSet rs) {
        if (rs != null) {
            try {
                rs.close();
            }catch(SQLException e){}
        }
    }
}