/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sat Jun 02 22:07:35 CDT 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package dao4j.orm;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Types;
import java.util.List;
import java.util.ArrayList;
import dao4j.*;
import dao4j.dao.TemaDAO;

/**
 * This class provides methods to populate DB Table of tema
 */
public class TemaDAOImpl implements TemaDAO {
    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO tema ("
        + "idTema, nombre, Curso_idCurso, examen_idexamen"
        + ") VALUES (?, ?, ?, ?)";

    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "idTema, nombre, Curso_idCurso, examen_idexamen "
        + "FROM tema WHERE "
        + "idTema = ? AND Curso_idCurso = ? AND examen_idexamen = ?";
    
    
    private static final String SQL_SELECT_ALL =
        "SELECT "
        + "idTema, nombre, Curso_idCurso, examen_idexamen "
        + "FROM tema"
        ;

    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE tema SET "
        + "nombre = ? "
        + "WHERE "
        + "idTema = ? AND Curso_idCurso = ? AND examen_idexamen = ?";

    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM tema WHERE "
        + "idTema = ? AND Curso_idCurso = ? AND examen_idexamen = ?";

    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Tema bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_INSERT);
            ps.setInt(1, bean.getIdtema());
            ps.setString(2, bean.getNombre());
            ps.setInt(3, bean.getCursoIdcurso());
            ps.setInt(4, bean.getExamenIdexamen());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    public Tema load(TemaKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT);
            ps.setInt(1, key.getIdtema());
            ps.setInt(2, key.getCursoIdcurso());
            ps.setInt(3, key.getExamenIdexamen());
            rs = ps.executeQuery();
            List results = getResults(rs);
            if (results.size() > 0)
                return (Tema) results.get(0);
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }
    
    public List<Tema> loadall(Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT_ALL);
            rs = ps.executeQuery();
            List results = getResults(rs);
            return results;
        }finally {
            close(rs);
            close(ps);
        }
    }

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void update(Tema bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_UPDATE);
            ps.setString(1, bean.getNombre());
            ps.setInt(2, bean.getIdtema());
            ps.setInt(3, bean.getCursoIdcurso());
            ps.setInt(4, bean.getExamenIdexamen());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(TemaKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_DELETE);
            ps.setInt(1, key.getIdtema());
            ps.setInt(2, key.getCursoIdcurso());
            ps.setInt(3, key.getExamenIdexamen());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }
    
    /**
     * Populate the ResultSet.
     * @param rs     The ResultSet.
     * @return       The Object to retrieve from DB.
     * @exception    SQLException if something is wrong.
     */
    protected List<Tema> getResults(ResultSet rs) throws SQLException {
        List results = new ArrayList<Tema>();
        while (rs.next()) {
            Tema bean = new Tema();
            bean.setIdtema(rs.getInt("idTema"));
            bean.setNombre(rs.getString("nombre"));
            if (rs.wasNull())
                bean.setNombre(null);     
            bean.setCursoIdcurso(rs.getInt("Curso_idCurso"));
            bean.setExamenIdexamen(rs.getInt("examen_idexamen"));
            results.add(bean);
        }
        return results;
    }

    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    protected void close(Statement stmt) {
        if (stmt != null) {
            try {
                stmt.close();
            }catch(SQLException e){}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    protected void close(ResultSet rs) {
        if (rs != null) {
            try {
                rs.close();
            }catch(SQLException e){}
        }
    }
}