/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Tue May 01 20:32:32 CDT 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.ipn.mx.model;

/*
 * For Table Pregunta
 */
public class Pregunta implements java.io.Serializable, Cloneable {
    private PreguntaKey _key = new PreguntaKey();

    /* idPregunta, PK */
    protected int idpregunta;

    /* texto */
    protected String texto;

    /* examen_idexamen, PK */
    protected int examenIdexamen;

    /* RespuestaCorrecta, PK */
    protected int respuestacorrecta;

    /* Return the key object. */
    public PreguntaKey getKeyObject() {
        return _key;
    }

    /* idPregunta, PK */
    public int getIdpregunta() {
        return idpregunta;
    }

    /* idPregunta, PK */
    public void setIdpregunta(int idpregunta) {
        this.idpregunta = idpregunta;
        _key.setIdpregunta(idpregunta);
    }

    /* texto */
    public String getTexto() {
        return texto;
    }

    /* texto */
    public void setTexto(String texto) {
        this.texto = texto;
    }

    /* examen_idexamen, PK */
    public int getExamenIdexamen() {
        return examenIdexamen;
    }

    /* examen_idexamen, PK */
    public void setExamenIdexamen(int examenIdexamen) {
        this.examenIdexamen = examenIdexamen;
        _key.setExamenIdexamen(examenIdexamen);
    }

    /* RespuestaCorrecta, PK */
    public int getRespuestacorrecta() {
        return respuestacorrecta;
    }

    /* RespuestaCorrecta, PK */
    public void setRespuestacorrecta(int respuestacorrecta) {
        this.respuestacorrecta = respuestacorrecta;
        _key.setRespuestacorrecta(respuestacorrecta);
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Pregunta))
            return false;

        Pregunta bean = (Pregunta) obj;

        if (this.idpregunta != bean.idpregunta)
            return false;

        if (this.texto == null) {
            if (bean.texto != null)
                return false;
        }
        else if (!this.texto.equals(bean.texto)) 
            return false;

        if (this.examenIdexamen != bean.examenIdexamen)
            return false;

        if (this.respuestacorrecta != bean.respuestacorrecta)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Pregunta bean = new Pregunta();
        bean.idpregunta = this.idpregunta;
        bean.texto = this.texto;
        bean.examenIdexamen = this.examenIdexamen;
        bean.respuestacorrecta = this.respuestacorrecta;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idpregunta").append(" = ").append(idpregunta).append("]").append(sep);
        sb.append("[").append("texto").append(" = ").append(texto).append("]").append(sep);
        sb.append("[").append("examenIdexamen").append(" = ").append(examenIdexamen).append("]").append(sep);
        sb.append("[").append("respuestacorrecta").append(" = ").append(respuestacorrecta).append("]").append(sep);
        return sb.toString();
    }
}