/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Tue May 01 20:32:32 CDT 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.ipn.mx.model;

/*
 * For Table Tema
 */
public class Tema implements java.io.Serializable, Cloneable {
    private TemaKey _key = new TemaKey();

    /* idTema, PK */
    protected int idtema;

    /* nombre */
    protected String nombre;

    /* Curso_idCurso, PK */
    protected int cursoIdcurso;

    /* examen_idexamen, PK */
    protected int examenIdexamen;

    /* Return the key object. */
    public TemaKey getKeyObject() {
        return _key;
    }

    /* idTema, PK */
    public int getIdtema() {
        return idtema;
    }

    /* idTema, PK */
    public void setIdtema(int idtema) {
        this.idtema = idtema;
        _key.setIdtema(idtema);
    }

    /* nombre */
    public String getNombre() {
        return nombre;
    }

    /* nombre */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /* Curso_idCurso, PK */
    public int getCursoIdcurso() {
        return cursoIdcurso;
    }

    /* Curso_idCurso, PK */
    public void setCursoIdcurso(int cursoIdcurso) {
        this.cursoIdcurso = cursoIdcurso;
        _key.setCursoIdcurso(cursoIdcurso);
    }

    /* examen_idexamen, PK */
    public int getExamenIdexamen() {
        return examenIdexamen;
    }

    /* examen_idexamen, PK */
    public void setExamenIdexamen(int examenIdexamen) {
        this.examenIdexamen = examenIdexamen;
        _key.setExamenIdexamen(examenIdexamen);
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Tema))
            return false;

        Tema bean = (Tema) obj;

        if (this.idtema != bean.idtema)
            return false;

        if (this.nombre == null) {
            if (bean.nombre != null)
                return false;
        }
        else if (!this.nombre.equals(bean.nombre)) 
            return false;

        if (this.cursoIdcurso != bean.cursoIdcurso)
            return false;

        if (this.examenIdexamen != bean.examenIdexamen)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Tema bean = new Tema();
        bean.idtema = this.idtema;
        bean.nombre = this.nombre;
        bean.cursoIdcurso = this.cursoIdcurso;
        bean.examenIdexamen = this.examenIdexamen;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idtema").append(" = ").append(idtema).append("]").append(sep);
        sb.append("[").append("nombre").append(" = ").append(nombre).append("]").append(sep);
        sb.append("[").append("cursoIdcurso").append(" = ").append(cursoIdcurso).append("]").append(sep);
        sb.append("[").append("examenIdexamen").append(" = ").append(examenIdexamen).append("]").append(sep);
        return sb.toString();
    }
}