/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Tue May 01 20:32:32 CDT 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.ipn.mx.orm;

import com.ipn.mx.model.Curso;
import com.ipn.mx.model.CursoKey;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Types;
import java.util.List;
import java.util.ArrayList;
import com.ipn.mx.dao.CursoDAO;

/**
 * This class provides methods to populate DB Table of Curso
 */
public class CursoDAOImpl implements CursoDAO {
    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO Curso ("
        + "idCurso, nombre, Usuario_idUsuarios"
        + ") VALUES (?, ?, ?)";

    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "idCurso, nombre, Usuario_idUsuarios "
        + "FROM Curso WHERE "
        + "idCurso = ? AND Usuario_idUsuarios = ?";

    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE Curso SET "
        + "nombre = ? "
        + "WHERE "
        + "idCurso = ? AND Usuario_idUsuarios = ?";

    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM Curso WHERE "
        + "idCurso = ? AND Usuario_idUsuarios = ?";

    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Curso bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_INSERT);
            ps.setInt(1, bean.getIdcurso());
            ps.setString(2, bean.getNombre());
            ps.setInt(3, bean.getUsuarioIdusuarios());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    public Curso load(CursoKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT);
            ps.setInt(1, key.getIdcurso());
            ps.setInt(2, key.getUsuarioIdusuarios());
            rs = ps.executeQuery();
            List results = getResults(rs);
            if (results.size() > 0)
                return (Curso) results.get(0);
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void update(Curso bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_UPDATE);
            ps.setString(1, bean.getNombre());
            ps.setInt(2, bean.getIdcurso());
            ps.setInt(3, bean.getUsuarioIdusuarios());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(CursoKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_DELETE);
            ps.setInt(1, key.getIdcurso());
            ps.setInt(2, key.getUsuarioIdusuarios());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }
    
    /**
     * Populate the ResultSet.
     * @param rs     The ResultSet.
     * @return       The Object to retrieve from DB.
     * @exception    SQLException if something is wrong.
     */
    protected List<Curso> getResults(ResultSet rs) throws SQLException {
        List results = new ArrayList<Curso>();
        while (rs.next()) {
            Curso bean = new Curso();
            bean.setIdcurso(rs.getInt("idCurso"));
            bean.setNombre(rs.getString("nombre"));
            bean.setUsuarioIdusuarios(rs.getInt("Usuario_idUsuarios"));
            results.add(bean);
        }
        return results;
    }

    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    protected void close(Statement stmt) {
        if (stmt != null) {
            try {
                stmt.close();
            }catch(SQLException e){}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    protected void close(ResultSet rs) {
        if (rs != null) {
            try {
                rs.close();
            }catch(SQLException e){}
        }
    }
}